# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Toffu < Formula
  desc "Woffu presence from your terminal"
  homepage "https://github.com/Madh93/toffu"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/Madh93/toffu/releases/download/v0.1.0/toffu_Darwin_arm64.tar.gz"
      sha256 "0873a9c3f4d5f435f9897af4ab3a3d5bb31c7a51d416278ecb24883a6a913554"

      def install
        bin.install "toffu"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Madh93/toffu/releases/download/v0.1.0/toffu_Darwin_x86_64.tar.gz"
      sha256 "3104d590af012c4e03240330f9758fed7a12c4924014529601da5e61f9ffe5ea"

      def install
        bin.install "toffu"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Madh93/toffu/releases/download/v0.1.0/toffu_Linux_arm64.tar.gz"
      sha256 "ede5f6419581b39c608021a4e0405e85f96de5cf2cdc34a00b69c98819f52aa5"

      def install
        bin.install "toffu"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Madh93/toffu/releases/download/v0.1.0/toffu_Linux_x86_64.tar.gz"
      sha256 "d9308864a68c6fefa33c2615cd783dac7603dc75e181faa4149b452d76637829"

      def install
        bin.install "toffu"
      end
    end
  end
end
