# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tpm < Formula
  desc "A package manager for Terraform providers"
  homepage "https://github.com/Madh93/tpm"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/Madh93/tpm/releases/download/v0.4.0/tpm_Darwin_arm64.tar.gz"
      sha256 "646222bfd0336089f060487d35d5fd71ae8fb828613aa0114a0a200ebf0cf8f1"

      def install
        bin.install "tpm"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Madh93/tpm/releases/download/v0.4.0/tpm_Darwin_x86_64.tar.gz"
      sha256 "79c876a75a844f197c6ec429e45a8c8653a088bcb1516b95f6e04ae95ec8ef55"

      def install
        bin.install "tpm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/Madh93/tpm/releases/download/v0.4.0/tpm_Linux_x86_64.tar.gz"
      sha256 "745101de14a3a3fb47417bffeb8b7f0c6a9a5d189b476aadb3404792c95317e7"

      def install
        bin.install "tpm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Madh93/tpm/releases/download/v0.4.0/tpm_Linux_arm64.tar.gz"
      sha256 "0bd533835bd3201d1929b5bbd690b52500ed096e3019195f68d8035b2fa336ec"

      def install
        bin.install "tpm"
      end
    end
  end
end
